### PR TITLE
Support Cycle Unified

### PR DESCRIPTION
**Pull request by grozen**
That's pretty much it. I need this in order to make cycle-canvas's sample project work now that I am also trying to make cycle-canvas support Cycle Unified. You could say it's a... vicious cycle.

Assuming you deem this worthy, I would also really appreciate it if you could publish this to NPM.

### CODE REVIEW

**Comment by Widdershin** [comment]
@grozen thanks for doing this. I was actually planning on sunsetting this library in favour of @cycle/time.

Could you try with Time.animationFrames() first, and if that doesn't work I can merge and release this.

**Comment by grozen** [comment]
Sure thing, I'll give it a spin and see if that fits the bill.

**Comment by grozen** [comment]
Unsurprisingly, I was able to use @cycle/time instead. Thanks for letting me know it's there ;)

**Comment by grozen** [comment]
No real need in merging this in, seeing how one could (and should) just use @cycle/time.

**Comment by Widdershin** [comment]
No worries, glad it worked. I need to add a notice to the README here
suggesting folk use cycle time instead

**Pull request closed without merging**
